x-uffizzi:
  ingress:
    service: one-api
    port: 80
    
services:
  one-api:
    image: justsong/one-api:latest
    container_name: one-api
    restart: always
    command: --log-dir /app/logs
    ports:
      - "80:3000"
    volumes:
      - app_data:/data
      - app_log:/app/logs
    environment:
      - SQL_DSN=root:123456@tcp(mysql:3306)/oneapi
      - REDIS_CONN_STRING=redis://redis:6379
      - SESSION_SECRET=zxdhqy999
      - TZ=Asia/Shanghai
      - SYNC_FREQUENCY=60
    networks:
      - net-one-api
    depends_on:
      - redis
      - mysql


  redis:
    image: redis:latest
    container_name: redis
    restart: always
    networks:
      - net-one-api
    
  mysql:
    image: mysql/mysql-server:8.0.23
    restart: always
    command: --bind-address=0.0.0.0
    container_name: ais-ninja-mysql
    environment:
      MYSQL_DATABASE: oneapi
      MYSQL_USER: root
      MYSQL_PASSWORD: zxd8200506
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_log:/etc/mysql/conf.d
    networks:
      - net-one-api

networks:
  net-one-api:
    driver: bridge

volumes:
  mysql_data:
  mysql_log:
  app_data:
  app_log:
