x-uffizzi:
  ingress:
    service: one-api
    port: 80
    
services:
  one-api:
    image: justsong/one-api:latest
    container_name: one-api
    restart: always
    command: --log-dir /app/logs
    ports:
      - "80:3000"
    volumes:
      - app_data:/data
      - app_log:/app/logs
    environment:
      # - SQL_DSN="${MY_SQL_DSN}
      - REDIS_CONN_STRING=redis://redis:6379
      - SESSION_SECRET=zxdhqy999
      - TZ=Asia/Shanghai
      - SYNC_FREQUENCY=60
    networks:
      - net-one-api
    secrets:
      - sql-dsn
    depends_on:
      - redis


  redis:
    image: redis:latest
    container_name: redis
    restart: always
    networks:
      - net-one-api
    
networks:
  net-one-api:
    driver: bridge

volumes:
  app_data:
  app_log:

secrets:
  sql-dsn:
    external: true
    name: "SQL_DSN"
